name: Build and Deploy

env:
  CLOUDFRONT_ID: "${{ secrets.CLOUDFRONT_ID }}"
  AWS_ACCESS_KEY: "${{ secrets.AWS_ACCESS_KEY }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Deploy to Staging
        run: npm run stage
