name: Screenshot Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  screenshot-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Build the site
      run: npm run build
    
    - name: Start local server
      run: |
        npm run preview &
        sleep 10
      env:
        NODE_ENV: production
    
    - name: Wait for server to be ready
      run: |
        timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'
    
    - name: Run screenshot tests
      run: npm run test:screenshots
      env:
        CI: true
    
    - name: Generate comparison report
      run: npm run test:screenshots:html
      if: always()
    
    - name: Upload screenshot artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: screenshot-comparisons
        path: test/screenshots/
        retention-days: 30
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  visual-regression:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: screenshot-tests
    if: always()
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Download screenshot artifacts
      uses: actions/download-artifact@v4
      with:
        name: screenshot-comparisons
        path: test/screenshots/
    
    - name: Generate detailed comparison report
      run: |
        npm run test:screenshots:html
        npm run test:screenshots:report
    
    - name: Comment PR with comparison results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Check if comparison report exists
          const reportPath = 'test/screenshots/comparison-report.json';
          if (fs.existsSync(reportPath)) {
            const report = JSON.parse(fs.readFileSync(reportPath, 'utf8'));
            
            let comment = `## 📸 Screenshot Comparison Results\n\n`;
            comment += `**Generated:** ${new Date(report.timestamp).toLocaleString()}\n`;
            comment += `**Total Comparisons:** ${report.totalComparisons}\n\n`;
            
            if (report.comparisons.length > 0) {
              comment += `### Comparison Summary\n\n`;
              comment += `| Page | Viewport | Local Size | Live Size | Difference |\n`;
              comment += `|------|----------|------------|-----------|------------|\n`;
              
              report.comparisons.forEach(comp => {
                const localSize = (comp.localSize / 1024).toFixed(1) + ' KB';
                const liveSize = (comp.liveSize / 1024).toFixed(1) + ' KB';
                const diff = comp.sizeDifference.percentage >= 0 ? '+' : '';
                const diffText = `${diff}${comp.sizeDifference.percentage.toFixed(1)}%`;
                
                comment += `| ${comp.name} | ${comp.viewport} | ${localSize} | ${liveSize} | ${diffText} |\n`;
              });
              
              comment += `\n### 📁 Artifacts\n`;
              comment += `- Screenshot comparisons are available in the workflow artifacts\n`;
              comment += `- HTML report: \`test/screenshots/comparison-report.html\`\n`;
              comment += `- JSON report: \`test/screenshots/comparison-report.json\`\n`;
            } else {
              comment += `No screenshot comparisons were generated. This might indicate an issue with the test setup.\n`;
            }
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          } else {
            console.log('No comparison report found');
          }